volumes:
  mongo_db:
services:
  mongodb:
    image: mongo:4.4.1
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'pass'
      MONGO_INITDB_DATABASE: 'product'
    ports:
      - '27017:27017'
    volumes:
      - ./src/config/init.js:/docker-entrypoint-initdb.d/init.js
      - mongo_db:/data/db
  price:
    image: adichallenge/adichallenge:product-engine
    container_name: price
    hostname: price
    ports:
      - '3000:3000'